-- HÁ 2 MANEIRAS DE DESCOBRIR O VALUE DA FAILSAFE STORAGE CONSUMPTION:




-- 1a MANEIRA) 



-- Storage usage on account level 


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE 
ORDER BY USAGE_DATE DESC;


-- STORAGE USAGE ON ACCOUNT LEVEL, FORMATTED 

SELECT USAGE_DATE,
        STORAGE_BYTES / (1024 * 1024 * 1024) AS STORAGE_GB,
        STAGE_BYTES / (1024 * 1024 * 1024) AS STAGE_DB,
        FAILSAFE_BYTES / (1024 * 1024 * 1024) AS FAILSAFE_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.STORAGE_USAGE
ORDER BY USAGE_DATE DESC;



-- STORAGE USAGE ON A TABLE LEVEL 


SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS;







-- STORAGE USAGE ON A TABLE, FORMATTED 

        SELECT 
        ID, 
        TABLE_NAME,
        TABLE_SCHEMA,
        ACTIVE_BYTES,
        TIME_TRAVEL_BYTES,
        FAILSAFE_BYTES / (1024 * 1024 * 1024) AS FAILSAFE_STORAGE_USED_GB
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
ORDER BY FAILSAFE_STORAGE_USED_GB DESC;





-- 2o method) USAR A GUI...


