




-- PARA MUDARMOS O TAMANHO DE 1 DE NOSSOS WAREHOUSES, PODEMOS RODAR 
-- COMANDOS SQL.
-- também podemos alterar esses tamanhos na GUI.
ALTER WAREHOUSE COMPUTE_WH
SET WAREHOUSE_SIZE = 'XSMALL';



ALTER WAREHOUSE COMPUTE_WH
SET WAREHOUSE_SIZE = 'SMALL';



