SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TCPH_SF1.CUSTOMER; 





-- AS QUERIES SQL, NO FORMATO SNOWFLAKE, POSSUEM UMA SINTAXE ESPECÍFICA, QUE É DIFERENTE DA SINTAXE SQL PADRÃO
-- SUA SINTAXE É SIMILAR A DE OBJETOS JAVASCRIPT (acessei a database SNOWFLAKE_SAMPLE_DATA, E ENTAO_ A TABLE TCPH_SF1, E DEPOIS A TABLE CUSTOMER)....